[2024-07-18 20:10:02,126] INFO _log() L224   * Detected change in '/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/app.py', reloading - call_trace=/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2024-07-18 20:10:03,346] ERROR log_exception() L1449 Exception on /deposit [POST] - call_trace=/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/app.py", line 82, in add_cash_to_user
    requests.post(transaction_endpoint + "transaction", body=payload_transaction)
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'body'
[2024-07-18 20:10:03,353] INFO _log() L224  127.0.0.1 - - [18/Jul/2024 20:10:03] "[35m[1mPOST /deposit HTTP/1.1[0m" 500 - - call_trace=/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2024-07-18 20:10:10,587] INFO _log() L224   * Detected change in '/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/app.py', reloading - call_trace=/Users/conradocosta/Desktop/MVP - MICROSSERVICÌ§OS/bank_service/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L224 
